### ISSUE TITLE
name 'np' is not defined - when calling ```TextPipelineArrayFeaturizer```

### ISSUE THREAD

**Issue by exfalsoquodlibet** [mamonu/textconsultations#21]
I got the above error when calling ```TextPipelineArrayFeaturizer``` which never occurred before.

I thought ```numpy``` was one of the required modules?

**Comment by exfalsoquodlibet** [comment]
You can see the full error in Example3 script

**Comment by mamonu** [comment]
has to do with notebook PATH vs other python sys path. 
Easy solution: just add   `import numpy as np` on the notebook for the time being.
I will find the way to auto-import np when loading any nlpfunctions submodule. It should happen beacuse its on __init__.py but somehow with notebooks it seems it doesnt.
